###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "messmer",
    "author": "hieuphaam",
    "url": "www.hieu23.com",
    "likes": 2343
}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "messmer",
    "name": "hieuphaam",
    "password": "ww2314234"
}